import { CM_CHIPS } from '@/data/quiz'

const scrollToInto = (id: string) => {
  const el = document.getElementById(id)
  if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' })
}

export default function CamnangTab() {
  return (
<div style={{ display: "flex", flexDirection: "column", gap: "14px" }}>
            <div style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "14px", padding: "10px 14px", display: "flex", flexWrap: "wrap", gap: "7px", alignItems: "center" }}>
              <span style={{ fontSize: "11.5px", fontWeight: "600", color: "#6B7080", letterSpacing: ".05em", textTransform: "uppercase", marginRight: "2px" }}>Nhảy tới</span>
              {CM_CHIPS.map((c) => (
                <button key={c.id} className="cm-chip" onClick={() => scrollToInto(c.id)}>{c.label}</button>
            ))}
            </div>
          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-khuvuc" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Cẩm nang nghiệp vụ sale</h2>
            <p style={{ margin: "0", color: "#6B7080", fontSize: "14px" }}>Từ điển thuật ngữ, kiến thức sản phẩm Phú Quốc, thư viện option, bảng giá tour trọn gói và FAQ — tổng hợp từ tài liệu training nội bộ. Số liệu chỉ để tham khảo: luôn kiểm tra bảng giá mới nhất trước khi báo khách.</p>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Khu vực Phú Quốc — chọn chỗ ở trước, xếp lịch trình sau</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khu vực</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Đặc điểm &amp; phù hợp với</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Dương Đông</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Trung tâm đảo: nhiều quán ăn, chợ đêm, tiện di chuyển và mua sắm. Phù hợp khách muốn tiện lợi, ăn uống đa dạng.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Sunset Town – An Thới</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Nam đảo: gần cáp treo Hòn Thơm, các show buổi tối (Kiss of the Sea, Symphony), nhiều điểm check-in. Phù hợp khách thích check-in và show diễn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Bắc đảo</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Khu vui chơi quy mô lớn: VinWonders, Safari, Grand World. Cách trung tâm khá xa — nên nghỉ gần khu khi có lịch trình Bắc đảo.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Bãi biển nghỉ dưỡng</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Resort ven biển, yên tĩnh, ít hàng quán bên ngoài. Phù hợp khách nghỉ dưỡng, gia đình có trẻ nhỏ.</td></tr>
            </table>
            <div style={{ marginTop: "10px", padding: "9px 12px", background: "#F4FBF9", border: "1px solid #D4EFE8", borderRadius: "12px", fontSize: "12px", color: "#1E6B5E", lineHeight: "1.6" }}>Khu vực ở quyết định lịch trình và chi phí di chuyển — hỏi vị trí khách sạn trước khi xếp tour, tránh khách đi đường ngược.</div>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-thuatngu" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Từ điển thuật ngữ</h2>
            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Thuật ngữ khách sạn</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Thuật ngữ</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Nghĩa và cách dùng</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Twin / Double room</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Phòng 2 giường đơn / phòng 1 giường đôi. Xác nhận rõ khi khách đi 2 người không phải cặp đôi.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>ABF (American Breakfast)</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bữa sáng kiểu Mỹ. Kiểm tra giá phòng đã gồm bữa sáng chưa (số bữa, số người) trước khi báo khách.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>High · Low · Peak season</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Mùa cao điểm, thấp điểm và đỉnh điểm (lễ Tết). Ảnh hưởng giá, tình trạng phòng và chính sách hủy.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Early C/I – Late C/O</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Nhận phòng sớm – trả phòng muộn. Phụ thuộc tình trạng phòng; phụ thu 30%, 50% hoặc 100% giá phòng tùy khung giờ. Giờ chuẩn: nhận từ 15:00, trả trước 12:00.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Walk-in</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Khách tự đến, chưa có đặt trước.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>N of G · N of Room</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Số khách – số phòng: hai con số luôn phải hỏi đủ khi nhận request.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>F&amp;B</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ăn uống – nhà hàng và bar trong khách sạn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>VAT invoice</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Hóa đơn VAT. Hỏi sớm khi khách cần về công ty hoặc báo cáo chi phí.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Housekeeping</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bộ phận buồng phòng. Liên quan khi khách xin nhận phòng sớm hoặc góp ý vệ sinh phòng.</td></tr>
            </table>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Thuật ngữ tour · vé · xe</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Thuật ngữ</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Nghĩa và cách dùng</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Cano · Speedboat</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Tàu cao tốc dùng trong tour biển. Lịch chạy phụ thuộc thời tiết.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Combo</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Gói ghép nhiều dịch vụ: phòng + vé + tour + xe. Hướng bán chính vì tăng giá trị booking và tiện cho khách.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Cut-off date</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Hạn cuối phải xác nhận hoặc thanh toán với đối tác, nếu không chỗ bị nhả lại.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Điểm đón · Pick-up point</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Nơi xe hoặc tàu đón khách. Xác nhận với khách trước ngày đi, kèm giờ có mặt.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Dinner show</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bữa tối kèm chương trình biểu diễn, ví dụ Sun Bavaria trong Night Paradise.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Free &amp; Easy</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Gói gồm phòng và vài dịch vụ cơ bản, khách tự do đi chơi, không theo đoàn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>HDV · Tour guide</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Hướng dẫn viên đi cùng đoàn. Tour ghép luôn có HDV; xe riêng thường chỉ có tài xế.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Itinerary · Lịch trình</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Trình tự điểm đến theo ngày và giờ. Sắp theo khu vực để khách không đi chặng ngược đường.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Landtour</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Phần dịch vụ tại điểm đến, không gồm vé máy bay.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>NL · TE · NCT</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Người lớn, trẻ em, người cao tuổi. Ba đối tượng có giá và điều kiện chứng từ khác nhau.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>PAX</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Số lượng khách. Dùng trong trao đổi nội bộ và báo giá dịch vụ.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Snorkeling</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Lặn ngắm san hô bằng ống thở, không cần bằng lặn. Có trong tour biển Nam đảo.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Tour ghép · Join tour</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ghép nhiều khách lẻ thành một đoàn, giá thấp hơn, lịch cố định.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Tour riêng · Private tour</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Chạy riêng cho một nhóm, linh hoạt giờ và điểm đến, giá cao hơn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Transfer</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dịch vụ đưa đón, thường là xe sân bay – khách sạn. Cần giờ bay và số hành lý.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Xe ghép · Xe riêng</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Đi chung tuyến với khách khác, hoặc xe phục vụ riêng theo lịch trình.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Yếu tố thời tiết</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Tour biển có thể hoãn hoặc đổi lịch do biến động. Nói trước với khách khi bán, không để khách bất ngờ.</td></tr>
            </table>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Thuật ngữ theo giai đoạn công việc</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Giai đoạn</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Thuật ngữ hay dùng</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Việc cần làm</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Tiếp nhận lead</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Lead, FIT/Group</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Trả lời trong 05 phút, xin ngày đi – về và số khách trước khi nói về giá.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Khai thác nhu cầu</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Sức chứa, loại giường, khu vực, ngân sách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Hỏi tuổi hoặc chiều cao trẻ em ngay từ đầu — cơ sở chia giá NL/TE/NCT.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Tư vấn option</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Option, lịch trình, combo, hạng vé</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Đề xuất 2–3 phương án theo khu vực ở và lịch bay của khách.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Báo giá &amp; chốt</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Báo giá, cut-off, chính sách hủy</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Gửi báo giá kèm bảng so sánh 2 gói. Chốt nhanh khi khách hỏi chi tiết.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Sau chuyến đi</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Feedback, review, khách quen</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Xin đánh giá và xin phép giữ liên lạc, để bán tiếp combo lần sau.</td></tr>
            </table>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-option" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Thư viện option ghép combo (11 option)</h2>
            <p style={{ margin: "0 0 6px", color: "#6B7080", fontSize: "12.5px" }}>Mỗi ngày trong combo chỉ chọn 01 chương trình full-day. Sale nắm tối thiểu 02 option cho từng vị trí bán chính: cáp treo – công viên nước, show diễn – ẩm thực đêm.</p>
            <div style={{ overflowX: "auto" }}>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px", minWidth: "700px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Mã</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Option · khung giờ</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Nội dung chính</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Phù hợp combo</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Lưu ý sale</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP01</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Hòn Thơm &amp; Aquatopia<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>08:30–16:30</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Cáp treo vượt biển, công viên nước, công viên chủ đề, tắm biển, Buffet Mango theo hạng vé.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Không ghép cùng tour tàu trong một ngày.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP02</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Nam đảo · 3 đảo<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>08:30–15:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Vào hang, câu cá, ngắm san hô, cano, ẩm thực hải sản.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Hỏi khách kỹ về chứng chỉ lặn và mức độ thoải mái trên biển.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP03</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Bắc đảo · Vinpearl<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>09:00–17:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>VinWonders, Safari, Grand World.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>3N2Đ → 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Cần trọn ngày; đừng ghép cùng tour biển.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP04</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Thủy địa · Làng chài Cù Lan<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>09:00–14:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Kayak, ngắm rừng nguyên sinh, đạp vịt.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 4N3Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Không phù hợp khách muốn tắm biển.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP05</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Sunset Town · Đảo Thơm<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>14:00–21:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bơi biển, ngắm hoàng hôn, dạo Sunset Town.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Không ghép thêm dịch vụ ăn tối trùng khung giờ.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP06</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Safari &amp; Grand World<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>09:00–16:30</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Xe đưa đón, tham quan Safari, xem show động vật.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>4N3Đ, 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Kiểm tra kỹ lịch bus nội khu trước khi hẹn giờ.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP07</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Grand World &amp; Tinh Hoa Việt Nam<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>16:30–21:30</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dạo Grand World, ăn tối, xem Tinh Hoa Việt Nam nếu có vé.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>4N3Đ, 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Phù hợp ngày nhận phòng Bắc đảo.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP08</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Night Paradise<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>16:30–21:30</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Kiss of the Sea, buffet tối, xem show biểu diễn.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 5N4Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Nên đặt trước ngày đi, chỗ ngồi có hạn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP09</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>3 đảo: Hòn Móng Rái – Gầm Ghì – Thơm<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>08:00–16:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Cano, tắm biển, ngắm san hô.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 4N3Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Hỏi khách việc say sóng trước khi chốt.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP10</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Ăn tối BBQ hải sản Sunset Town<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>18:00–21:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Buffet/BBQ hải sản, nhạc sống.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Tất cả combo</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Nên đặt trước; hỏi khách dị ứng hải sản.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>OP11</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>Tour câu mực đêm<div style={{ fontWeight: "400", color: "#6B7080", fontSize: "12px", marginTop: "2px" }}>18:30–22:00</div></td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Câu mực, nấu mực, ngắm đêm biển.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#6B7080", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>2N1Đ → 4N3Đ</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#B4441F", verticalAlign: "top", lineHeight: "1.45", fontSize: "12.5px" }}>Có thể hoãn do thời tiết — nói trước với khách.</td></tr>
            </table>
            </div>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Điểm đến và câu hỏi cần đặt</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Điểm đến</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Trải nghiệm</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Cần hỏi khách</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Hòn Thơm</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Cáp treo vượt biển, Aquatopia, tắm biển. Vé cáp treo đơn thuần hoặc kèm buffet.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ngày đi, chiều cao trẻ em, có dùng buffet không.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Night Paradise</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Kiss of the Sea, dạo đèn LED, show diễn phụ, bán kèm ăn tối.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có cần ăn tối không, muốn xem show phụ nào.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Sunset Town &amp; Grand World</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dạo phố, Cầu Hôn, show Tinh Hoa Việt Nam, kênh đào.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ngày nhận/trả phòng khu nào, có đi ban đêm được không.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>VinWonders</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Công viên chủ đề lớn nhất Việt Nam. Trẻ dưới 1m miễn phí.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Số trẻ em và chiều cao, ngày đi.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Safari</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Xe ô tô Safari, xem động vật quý hiếm. Không chạm tay vào hàng rào.</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ngày đi, lịch mở cửa.</td></tr>
            </table>
            <div style={{ marginTop: "10px", padding: "9px 12px", background: "#F4FBF9", border: "1px solid #D4EFE8", borderRadius: "12px", fontSize: "12px", color: "#1E6B5E", lineHeight: "1.6" }}>Sau khi đọc: bán cái khách cần — mỗi điểm đến gắn một câu hỏi.</div>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-giatour" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Bảng giá tour trọn gói (tham khảo)</h2>
            <p style={{ margin: "0 0 6px", color: "#6B7080", fontSize: "12.5px" }}>Giá trọn gói đã gồm vé máy bay, khách sạn 4–5 sao, ăn theo chương trình, xe và hướng dẫn viên. Số liệu tham khảo — giá thay đổi theo mùa, tình trạng chỗ và thời điểm đặt; giá cuối được xác nhận khi chốt tour.</p>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Tour 3N2Đ</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Số lượng khách</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khách Việt (VNĐ/khách)</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khách nước ngoài (USD/khách)</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>2 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>8.490.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>429</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>4 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>6.290.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>319</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>6 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>5.290.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>269</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>8 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>4.990.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>259</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>10 khách trở lên</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>4.590.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>239</td></tr>
            </table>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Tour 2N1Đ</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Số lượng khách</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khách Việt (VNĐ/khách)</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khách nước ngoài (USD/khách)</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>2 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>6.290.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>319</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>4 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>4.990.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>259</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>6 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>4.590.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>239</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>8 khách</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>4.290.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>219</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>10 khách trở lên</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>3.990.000</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>209</td></tr>
            </table>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Phụ thu &amp; chính sách trẻ em (tour trọn gói)</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khoản</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Mức áp dụng</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Phụ thu phòng đơn</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>1.200.000đ / 2N1Đ · 1.900.000đ / 3N2Đ · 2.600.000đ / 4N3Đ</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Phụ thu khách nước ngoài</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>20 USD/khách/đêm (phụ thu vé máy bay và giá phòng)</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Trẻ em tour</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dưới 2 tuổi miễn phí · 2–5 tuổi 50% giá tour · 6–11 tuổi 75% · 12 tuổi trở lên như người lớn</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Ngày lễ, Tết</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Báo giá riêng theo thời điểm</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Giá tour đã gồm</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Xe đưa đón, HDV, phí tham quan, ăn theo chương trình, thuế và phí</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Chưa gồm</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Chi phí cá nhân, tip HDV/tài xế, dịch vụ ngoài chương trình</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Hoàn hủy tour</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Trước 7 ngày hoàn 100% tiền cọc · trong 7 ngày hoàn 50% · trong 72 giờ không hoàn tiền</td></tr>
            </table>
            <div style={{ marginTop: "10px", padding: "9px 12px", background: "#FFF6F3", border: "1px solid #F6D9CF", borderRadius: "12px", fontSize: "12px", color: "#B4441F", lineHeight: "1.6" }}>Báo giá luôn kèm chính sách trẻ em và phụ thu để tránh tranh chấp về sau. Với nhóm trên 10 khách, liên hệ bộ phận giá để có giá tốt trước khi báo khách.</div>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-diadiem" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Địa điểm nổi bật Phú Quốc</h2>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Địa điểm</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Nổi bật với</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Bãi Sao</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Biển đẹp nhất Nam đảo, bãi cát trắng mịn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Bãi Kem</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>View hoàng hôn đẹp, nhiều nhà hàng.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Hòn Móng</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ghép thuyền, lặn ngắm san hô.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Cửa Cạn</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Ngắm hoàng hôn, chợ nổi, làng chài.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Bãi Xếp Ngói</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Biển đẹp miền Bắc, check-in đẹp.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Grand World</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>“Thành phố không ngủ”.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Sunset Town</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Thị trấn hoàng hôn, Cầu Hôn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Cáp treo Hòn Thơm</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dài nhất thế giới (7.899,9m).</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>VinWonders / Safari</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Khu vui chơi, động vật bán hoang dã.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Chợ đêm Phú Quốc</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Hải sản, đặc sản.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Nhà thùng nước mắm · nuôi cấy ngọc trai</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Tham quan nghề truyền thống.</td></tr>
            </table>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-xuly" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Xử lý phản hồi tiêu cực — 6 bước</h2>
            <p style={{ margin: "0 0 6px", color: "#6B7080", fontSize: "12.5px" }}>Ví dụ mẫu: khách phàn nàn phòng bẩn. Phản hồi khách trong 15 phút, xử lý dứt điểm trong 24h.</p>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Bước</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Việc làm</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>1 · Ghi nhận &amp; xin lỗi</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>“Em xin lỗi vì trải nghiệm chưa tốt. Em ghi nhận ngay ạ.”</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>2 · Hỏi rõ sự việc</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Xin thêm hình ảnh hoặc thời điểm phát hiện để xử lý nhanh.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>3 · Báo cấp trên</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Báo quản lý, phối hợp khách sạn hoặc đối tác liên quan.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>4 · Đưa phương án</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Đổi phòng, dọn lại, tặng quà, giảm giá, hoàn tiền một phần tùy mức độ — cập nhật cho khách.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>5 · Theo dõi đến cùng</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Kiểm tra kết quả, không để khách phải nhắc lần 2.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>6 · Chốt &amp; ghi nhận</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Lưu hồ sơ sự cố, rút kinh nghiệm cho lần sau.</td></tr>
            </table>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-faq" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Câu hỏi thường gặp (FAQ)</h2>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Khách hỏi</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Trả lời</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Tour có gồm vé máy bay không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, giá trọn gói gồm vé máy bay khứ hồi, khách sạn, ăn theo chương trình, xe đưa đón và HDV.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Trẻ em tính giá thế nào?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dưới 2 tuổi miễn phí (không chiếm chỗ) · 2–5 tuổi 50% giá tour · 6–11 tuổi 75% · 12 tuổi trở lên như người lớn.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Đi mùa nào đẹp nhất?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Tháng 11–4: biển êm, trời trong. Tháng 5–10 là mùa mưa, gió tây nam.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Muốn thay đổi lịch trình?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có thể, báo trước 3 ngày, tùy tình trạng dịch vụ.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Có HDV tiếng Anh không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, phụ thu ngoài giờ, báo trước 3 ngày.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Có ăn chay không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, báo trước khi đặt tour, không phát sinh phụ thu (tùy menu).</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Muốn phòng hạng cao hơn?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Nâng hạng khi còn chỗ, trả phần chênh lệch.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Có bị ghép khách lạ không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Tour ghép (join) có thể có khách lạ; tour riêng (private) không ghép.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Giờ nhận / trả phòng?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Nhận phòng 14:00, trả phòng 12:00; trả muộn phụ thu theo quy định.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Chính sách hủy tour?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Trước 7 ngày hoàn 100% tiền cọc · trong 7 ngày hoàn 50% · trong 72 giờ không hoàn tiền. Bất khả kháng (thiên tai, bão): hai bên thương lượng.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Xuất hóa đơn VAT?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, cần mã số thuế công ty, báo trước 3 ngày.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Có đón tại khách sạn không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, đón tại khách sạn/sân bay miễn phí trong khu vực hỗ trợ.</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#2A2D5C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600", whiteSpace: "nowrap" }}>Phải đặt cọc ngay không?</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Có, cọc 30% để giữ chỗ và giữ giá.</td></tr>
            </table>
          </section>

          <section style={{ background: "#fff", border: "1px solid #E6E8EF", borderRadius: "16px", padding: "clamp(13px,3vw,18px)" }}>
            <h2 id="cm-thunhap" style={{ fontFamily: "Outfit,sans-serif", fontSize: "18px", fontWeight: "600", color: "#2A2D5C", margin: "0 0 2px" }}>Thu nhập &amp; quy chế hoa hồng (giai đoạn đầu)</h2>
            <p style={{ margin: "0 0 6px", color: "#6B7080", fontSize: "12.5px" }}>Tổng thu nhập = Lương cứng 4.000.000đ + Hoa hồng Tour + Hoa hồng ELYDAY. Doanh thu Tour và ELYDAY cộng gộp khi xét target.</p>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Target doanh thu theo tháng</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Giai đoạn</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Target tối thiểu/tháng</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Ý nghĩa</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Thử việc – Tháng 1</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>100 triệu</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Điều kiện tiếp tục tháng 2</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Thử việc – Tháng 2</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>150 triệu</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Điều kiện đạt thử việc</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Chính thức – Từ tháng 3</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>200 triệu</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Duy trì và đánh giá định kỳ</td></tr>
            </table>
            <p style={{ margin: "8px 0 0", color: "#6B7080", fontSize: "13px" }}>Đạt: từ 100% target · Cần cải thiện: 70% đến dưới 100% · dưới 70% trong 2 tháng liên tiếp: xem xét lại vị trí.</p>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Hoa hồng Tour — tính trên lợi nhuận gộp/tháng</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Lợi nhuận gộp Tour/tháng</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Tỷ lệ</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dưới 40 triệu</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>0%</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Từ 40 triệu trở lên</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#1E6B5E", verticalAlign: "top", lineHeight: "1.45", fontWeight: "600" }}>10% × toàn bộ lợi nhuận gộp Tour</td></tr>
            </table>

            <h3 style={{ fontFamily: "Outfit,sans-serif", fontSize: "14px", fontWeight: "600", color: "#2A2D5C", margin: "14px 0 7px" }}>Hoa hồng ELYDAY — lũy tiến theo doanh thu booking chốt trong tháng</h3>
            <table style={{ width: "100%", borderCollapse: "collapse", fontSize: "12.5px" }}>
              <tr><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Doanh thu booking/tháng</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Tháng 05–10</th><th style={{ textAlign: "left", padding: "5px 8px", background: "#F5F6FA", color: "#2A2D5C", fontWeight: "600", borderBottom: "1px solid #E6E8EF", verticalAlign: "top" }}>Tháng 11–04</th></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bậc 1</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dưới 150 triệu: 0</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Dưới 200 triệu: 0</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bậc 2</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>150 → &lt;200 triệu: 1%</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>200 → &lt;300 triệu: 1%</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bậc 3</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>200 → &lt;500 triệu: 2tr×1% + phần vượt 200tr×1,5%</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>300 → &lt;500 triệu: 3tr×1% + phần vượt 300tr×1,5%</td></tr>
              <tr><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Bậc 4</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Từ 500 triệu: + phần vượt 500tr×2%</td><td style={{ padding: "5px 8px", borderBottom: "1px solid #EEF0F5", color: "#3A3E4C", verticalAlign: "top", lineHeight: "1.45" }}>Từ 500 triệu: + phần vượt 500tr×2%</td></tr>
            </table>
            <div style={{ marginTop: "10px", padding: "9px 12px", background: "#F4FBF9", border: "1px solid #D4EFE8", borderRadius: "12px", fontSize: "12px", color: "#1E6B5E", lineHeight: "1.6" }}>Booking được tính là đã chốt khi dịch vụ xác nhận trên hệ thống và khách đã thanh toán cọc theo chính sách. Booking hủy/hoàn/giảm giá sau khi ghi nhận sẽ được điều chỉnh vào kỳ đối soát tiếp theo. Hoa hồng chi sau khi Kế toán đối soát.</div>
          </section>
        </div>
  )
}
